apiVersion: v1
kind: ReplicationController
metadata:
  name: testdemo3333
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: testdemo3333
  template:
    metadata:
      labels:
        app: testdemo3333
    spec:
      serviceAccount: YOUR
      containers:
      - name: testdemo3333
        image: ${docker-registry}/${docker-namespace}/testdemo3333:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080